#! /usr/bin/tcsh
date
source /home/mta/.ascrc
/home/mta/bin/reset_param
punlearn dataseeker
pset dataseeker repository="/data/mta/DataSeeker/data/repository"
setenv IDL_PATH "+/home/mta/IDL:${IDL_PATH}"
setenv IDL_PATH "+/usr/local/rsi/user_contrib/astron_Oct09/pro:+/home/mta/IDL:+/home/nadams/pros:+/data/swolk/idl_libs:/home/mta/IDL/tara:widget_tools:utilities:event_browser"
